# Generated by Django 4.0.6 on 2022-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('service_man', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
